import { chromium } from 'file:///C:/Users/Pro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'

const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' })
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' })
await page.evaluate(() => localStorage.clear())
await page.reload({ waitUntil: 'networkidle' })

const assert = (condition, message) => { if (!condition) throw new Error(message) }
assert(await page.getByText('今日主线').isVisible(), '今日页面没有显示')
assert(await page.getByRole('heading', { name: '今日任务' }).isVisible(), '今日任务分区缺失')
assert(await page.getByRole('heading', { name: '学习副本' }).isVisible(), '学习副本没有独立分区')
await page.getByRole('button', { name: '切换到夜晚模式' }).click()
assert(await page.locator('.phone-frame.theme-dark').count() === 1, '夜晚模式没有生效')
await page.getByRole('button', { name: '切换到白天模式' }).click()

const firstTask = page.locator('.task-card').first()
await firstTask.getByRole('button', { name: '更多操作' }).click()
await page.getByRole('button', { name: '修改任务' }).click()
await page.locator('.task-modal input').first().fill('完成第二版体验反馈')
await page.getByRole('button', { name: /保存修改/ }).click()
assert(await page.getByText('完成第二版体验反馈').isVisible(), '任务修改未保存')

await page.locator('.bottom-nav button').filter({ hasText: '日程' }).click()
assert(await page.locator('.week-strip i').count() === 1, '没有任务的日期错误显示了圆点')
await page.locator('.page-header .icon-button').click()
await page.getByRole('button', { name: '下个月' }).click()
const calendarDay = page.locator('.calendar-grid button').first()
await calendarDay.click()
assert(await calendarDay.getAttribute('class').then((value) => value?.includes('selected')), '月历日期无法点击切换')
await page.locator('.page-header .icon-button').click()
await page.locator('.week-strip button').first().click()
const cards = page.locator('.schedule-card')
const before = await cards.first().getAttribute('data-task-id')
const handle = cards.first().getByRole('button', { name: /长按拖动/ })
const target = cards.nth(1)
const hb = await handle.boundingBox(); const tb = await target.boundingBox()
if (hb && tb) {
  await page.mouse.move(hb.x + hb.width / 2, hb.y + hb.height / 2)
  await page.mouse.down(); await page.waitForTimeout(380)
  await page.mouse.move(tb.x + tb.width / 2, tb.y + tb.height / 2, { steps: 5 }); await page.mouse.up()
}
assert((await cards.first().getAttribute('data-task-id')) !== before, '长按拖动没有改变顺序')

await page.locator('.fab').click()
await page.getByPlaceholder('输入一个清晰、可完成的任务').fill('每周复盘')
await page.getByRole('button', { name: /重复与积压/ }).click()
await page.locator('.advanced-panel input[type="checkbox"]').first().check()
assert(await page.getByText('每周哪几天').isVisible(), '重复任务没有星期设置')
assert(await page.getByText('开始日期').isVisible() && await page.getByText('截止日期').isVisible(), '重复任务缺少起止日期')
await page.getByRole('button', { name: /发布任务/ }).last().click()

await page.locator('.fab').click()
await page.getByPlaceholder('输入一个清晰、可完成的任务').fill('截止时间测试任务')
await page.getByRole('button', { name: /截止时间/ }).click()
await page.getByRole('spinbutton', { name: '自定义任务积分' }).fill('17')
const today = await page.evaluate(() => { const d = new Date(); const o = d.getTimezoneOffset(); return new Date(d.getTime() - o * 60000).toISOString().slice(0, 10) })
await page.locator('.deadline-fields input[type="date"]').fill(today)
await page.locator('.deadline-fields input[type="time"]').fill('23:59')
await page.getByRole('button', { name: /发布任务/ }).last().click()
assert(await page.getByText('截止时间测试任务').isVisible(), '截止时间任务没有出现在当日日程')
assert(await page.getByText('+17').isVisible(), '自定义任务积分没有生效')

await page.locator('.bottom-nav button').filter({ hasText: '奖励' }).click()
await page.getByRole('button', { name: /自定义新奖励/ }).click()
await page.getByPlaceholder('例如：吃一顿大餐').fill('周末喝一杯奶茶')
await page.getByRole('button', { name: '加入奖励库' }).click()
assert(await page.getByText('周末喝一杯奶茶').isVisible(), '自定义奖励没有加入奖励库')
const customReward = page.locator('.reward-card').filter({ hasText: '周末喝一杯奶茶' })
await customReward.getByRole('button', { name: '管理奖励' }).click()
await page.getByRole('button', { name: '修改奖励' }).click()
await page.locator('.reward-modal input').nth(1).fill('周末奶茶券')
await page.getByRole('button', { name: '保存奖励' }).click()
assert(await page.getByText('周末奶茶券').isVisible(), '奖励修改未保存')

await page.locator('.bottom-nav button').filter({ hasText: '成长' }).click()
assert(await page.getByRole('heading', { name: '任务警告' }).isVisible(), '任务警告模块缺失')
assert(await page.getByText('截止时间测试任务').isVisible(), '48小时内截止任务没有进入警告')
await page.getByRole('button', { name: '切换到夜晚模式' }).click()
assert(await page.locator('.phone-frame.theme-dark').count() === 1, '成长页日夜模式按钮失效')
await page.getByRole('button', { name: '切换到白天模式' }).click()
await page.getByRole('button', { name: /累计完成任务数/ }).click()
assert(await page.locator('.detail-modal').getByText('累计完成任务数').isVisible(), '累计数据不可点击查看历史')
await page.locator('.detail-header button').click()
await page.getByRole('button', { name: /任务历史/ }).click()
assert(await page.locator('.detail-modal').getByText('累计完成任务数').isVisible(), '任务历史按钮没有响应')
await page.locator('.detail-header button').click()
await page.getByRole('button', { name: /数据备份/ }).click()
assert(await page.getByRole('heading', { name: '数据备份' }).isVisible(), '数据备份按钮没有响应')
assert(await page.getByRole('button', { name: /导出全部数据/ }).isVisible(), '数据导出入口缺失')
await page.locator('.detail-header button').click()
await page.locator('.reset-entry').click()
assert(await page.getByRole('heading', { name: '恢复初始状态' }).isVisible(), '成长页没有直接的恢复初始状态入口')
await page.getByPlaceholder('确认重置').fill('确认重置')
await page.getByRole('button', { name: '永久清除并恢复初始状态' }).click()
assert(await page.getByText('完成产品原型体验反馈').isVisible(), '恢复初始状态没有重建初始数据')
await page.screenshot({ path: 'preview-v2.png', fullPage: true })

await browser.close()
console.log('V4 smoke test passed: custom points, deadline task, time, interactive calendar, warning panel, theme, backup and reset')

